SELECT EMPLOYEE_ID,
       LAST_NAME,
       JOB_ID,
       HIRE_DATE AS STARTDATE
FROM EMPLOYEES;


SELECT DISTINCT JOB_ID
FROM EMPLOYEES;


SELECT EMPLOYEE_ID AS "Emp #",
       LAST_NAME AS "Employee",
       JOB_ID AS "Job",
       HIRE_DATE AS "Hire Date"
FROM EMPLOYEES;