1)

SELECT table_name
FROM user_tables;

DESC DEPT;

SELECT * FROM DEPT;

DROP TABLE DEPT CASCADE CONSTRAINTS;


CREATE TABLE DEPT (
    DEPT_ID NUMBER(7) PRIMARY KEY,
    DEPT_NAME VARCHAR2(20)
);

DESC DEPT;

2)

INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (10, 'Accounts');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (NULL, 'IT');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (20, 'IT');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES ('A1', 'Accounts');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME)
VALUES (30, 'Accounts');

SELECT * FROM DEPT;


3)

CREATE TABLE EMP (
    ID NUMBER(7) PRIMARY KEY,
    LAST_NAME VARCHAR2(25) NOT NULL,
    FIRST_NAME VARCHAR2(25),
    DEPT_ID NUMBER(7),
    CONSTRAINT EMP_DEPT_FK
    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPT(DEPT_ID)
);

DESC EMP;

INSERT INTO EMP
VALUES (101, 'Sam', 'Sundar', 10);
INSERT INTO EMP
VALUES (102, 'Ram', 'Krishna', 20);
INSERT INTO EMP
VALUES (103, 'Gopi', NULL, 40);
INSERT INTO EMP
VALUES (103, 'Gopi', NULL, 30);
INSERT INTO EMP
VALUES (104, NULL, 'Ram', 20);
INSERT INTO EMP
VALUES (104, 'Kumar', 'Ram', 20);

SELECT * FROM EMP;